name: stream_feed
description: Stream Feed official Dart SDK. Build your own feed experience using
  Dart and Flutter.
version: 0.6.0+3
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  dio: ^5.0.0
  equatable: ^2.0.5
  faye_dart:
    path: ../faye_dart
  http_parser: ^4.0.2
  intl:
  jose: ^0.3.3
  json_annotation: ^4.8.0
  logging: ^1.1.1
  meta: ^1.8.0
  mime: ^1.0.4

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.23.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
